repeat task.wait() until game:IsLoaded()
_G.TekkitConfig = {
  AutoFarm = true,
  AutoFarmOptions = {
    "Close GUI",
    "Fail Safe",
  },
  AutoPrestige = true,
  PrestigeBoost = "Gold Boost",
  PrestigeToStopAt = 5,
  PrestigeGold1 = 80000000,
  PrestigeGold2 = 160000000,
  PrestigeGold3 = 600000000,
  PrestigeGold4 = 800000000,
  PrestigeGold5 = 1000000000,
  AutoStart = true,
  AutoStartType = "Missions",
  AutoStartMap = "Shiganshina",
  AutoStartObjective = "Breach",
  AutoStartDifficulty = "Hardest",
  PlayBoostedMap = false,
  AutoStartModifiers = {
    "No Skills",
    "No Talents",
    "Nightmare",
    "Oddball",
    "Injury Prone",
    "Chronic Injuries",
    "Fog",
    "Glass Cannon",
    "Time Trial",
  },
  AutoReload = true,
  SafetyTime = 21,
  MultiHit = 9,
  DisableHovering = true,
  HitDistance = 1000,
  BossDamage = 9,
  AutoReturn = true,
  ReturnAmount = 15,
  StreakAmount = 100000,
  StreakDie = true,
  WaveToDieAt = 0,
  AutoWaveDie = false,
  WavesRollBlessing = false,
  WavesBuyUpgrades = false,
  WavesAutoUpgrade = false,
  WavesAutoSkip = false,
  WavesGetCrates = false,
  WavesUpgradesToBuy = {
  },
  ClaimQuests = true,
  ClaimAchievements = true,
  UseSkills = false,
  EquipSkills = true,
  Skills = {
    "Drill Thrust",
    "Torrential Steel",
    "Let it RIP",
    "Red Flare",
    "Black Flare",
    "Order: Rage",
    "Rage Mode"
  },
  AutoSpearQuests = false,
  EquipSpears = false,
  EnhancePerk = true,
  PerkToEnhance = "Body",
  PerksToUse = {
    "Common",
    "Rare"
  },
  EquipPerks = true,
  BodySlot = "Heavenly Restriction",
  OffenseSlot = "Kengo",
  DefenseSlot = "",
  SupportSlot = "",
  DeletePerks = true,
  RarityToDelete = {
    "Common",
    "Rare",
    "Epic"
  },
  UpgradeGear = true,
  AutoSkillTree = true,
  LeftPath = "Skill Cooldown",
  MiddlePath = "Damage",
  RightPath = "Damage Reduction",
  PathPriority = "Middle",
  RollCooldown = 3,
  RollFamily = false,
  BuyBoosts = true,
  ItemtoBuyWith = "Canes",
  Boosts = {
    "2x Gold Boost [2h]"
  },
  HoverHeight = 265,
  HoverSpeed = 3000,
  NoTitanLag = true,
  TitanEsp = false,
  NapeExtend = false,
  DisableRendering = true,
  Webhook = true,
  WebhookLink = "https://discord.com/api/webhooks/1506142435309391934/5F4iIYLiuhgbyq5zzamoIoXAPPXMOUunuNIUKxbbltGucYyHjTMb1bcL_49Yo9fpI0F8",
  ShowUsername = true,
  SendSafetyUpdate = true,
  OnikiriRejoin = false,
  DeusRejoin = false,
  JotunnRejoin = false,
  PrivateServerCode = "-",
  LeaveIfMorePlayers = true,
  AutoSelectSlot = true,
  Slot = "B",

}
script_key="hcVRWWqjTNhdINverKhTdhtawQspzpkT";
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/5bfd68232034676923088ca8b6698be7.lua"))()
