local Players = game:GetService("Players")

Players.PlayerAdded:Connect(function(Player)
	task.wait(10)
	print(1)
	task.wait(10)
	print(2)
	task.wait(10)
	print(3)
	Player:Kick("sw ngu bi ket lever")
end)
